### ISSUE TITLE
What are the goals for this project?

### ISSUE THREAD

**Issue by duoi** [WardPearce/Materialious#1]
Let me start off by saying this is phenomenal work, I can't wait to run something like this. The current Invidious UI leaves a lot to be desired.

I'm curious what the usage intention is behind the project. That is, is this intended to be a standalone deployment of Invidious with a more fleshed out theme? Or is this intended to act as an alternative interface for existing Invidious deployments where the Invidious target instance can be set as a setting?

Thanks for all of your work in this space!

**Comment by WardPearce** [comment]
Thanks for your interest! This project is a custom interface for Invidious, what requires you to host your own instance of Invidious. 

Due to CORS & Invidious limitions on modifying them, this project requires a reverse proxy (e.g. caddy or nginix) to overwrite CORS to allow auth from another domain or sub domain (e.g. Materialious).

If you are using a Invidious instance you don't ask, you'll have to ask the site owners to host Materialious.
